backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Home'
        name: 'home'
        file: 'src/posts/mypost.md'
        create: true
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Author', name: 'author', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown', required: true }
