backend:
  # name: test-repo
  name: git-gateway
  branch: main
media_folder: public/img/publications
collections:
  - name: 'home'
    label: 'Home'
    files:
      - label: 'Home'
        name: 'home'
        file: 'src/contents/pages/home.md'
        fields:
          - { label: 'Page title', name: 'pageTitle', widget: 'string' }
          - { label: 'Top text', name: 'topText', widget: 'string' }
          - { label: 'Main text', name: 'mainText', widget: 'string' }
          - { label: 'Bottom text', name: 'bottomText', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown', required: true }
  - name: 'about'
    label: 'About'
    files:
      - label: 'About'
        name: 'about'
        file: 'src/contents/pages/about.md'
        fields:
          - { label: 'Page title', name: 'pageTitle', widget: 'string' }
          - { label: 'Top text', name: 'topText', widget: 'string' }
          - { label: 'Main text', name: 'mainText', widget: 'string' }
          - { label: 'Bottom text', name: 'bottomText', widget: 'string' }
          - label: 'Stacks'
            name: 'stacks'
            widget: list
            field: { widget: 'string' }
  - name: 'post'
    label: 'Post'
    # folder: 'src/posts'
    folder: 'src/contents/posts/'
    slug: '{{slug}}'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'MinToRead', name: 'minToRead', widget: 'number' }
      - {
          label: 'Level',
          name: 'level',
          widget: 'select',
          options: ['Iniciante', 'Médio', 'Avançado'],
        }
      - {
          label: 'Stacks',
          name: 'stacks',
          widget: 'select',
          required: false,
          multiple: true,
          options:
            [
              'ReactJs',
              'NextJs',
              'NodeJs',
              'Laravel',
              'VueJs',
              'Firebase',
              'Sql',
              'DotNet',
              'Typescript',
            ],
        }
      - {
          label: 'Featured Image',
          name: 'thumbnail',
          widget: 'image',
          required: false,
        }
      - {
          label: 'Publish Date',
          name: 'publishDate',
          widget: 'datetime',
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
    sortableFields: ['title', 'author']
