backend:
  name: test-repo
  # name: git-gateway
  branch: main
media_folder: public/img
collections:
  - name: 'home'
    label: 'Home'
    files:
      - label: 'Home'
        name: 'home'
        file: 'src/contents/posts/home.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Author', name: 'author', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown', required: true }

  - name: 'post'
    label: 'Post'
    folder: 'src/posts'
    slug: '{{slug}}'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
    sortableFields: ['title', 'author']
